############################################################
# Dockerfile to prepare variables
############################################################

FROM debian:11

CMD cd /app && \
dockerfiles/prepare-vars/prepare-vars.sh && \
echo "All done" && \
exit