# directory
CONFIG_FILE_PATH = "./data/config.json"
DB_PATH = "./data/sdk.db"
GEOIP2_DB_PATH = "./data/GeoLite2-Country.mmdb"


# response
RES_SUCCESS = 0
RES_FAIL = -1
RES_CANCEL = -2
RES_NO_SUCH_METHOD = -10
RES_LOGIN_BASE = -100
RES_LOGIN_FAILED = -101
RES_LOGIN_CANCEL = -102
RES_LOGIN_ERROR = -103
RES_LOGOUT_FAILED = -104
RES_LOGOUT_CANCEL = -105
RES_LOGOUT_ERROR = 106
RES_EXIT_FAILED = -110
RES_EXIT_NO_DIALOG = -111
RES_EXIT_CANCEL = -112
RES_EXIT_ERROR = -113
RES_INIT_FAILED = -114
RES_INIT_ERROR = -115
RES_LOGIN_FORBIDDED = -117

RES_SDK_VERIFY_SUCC = 0
RES_SDK_VERIFY_FAIL = 1